# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "GDG CloudFest"
#email: "canelaguil@gmail.com"
description: "GDG CloudFest is the biggest Google Cloud gathering yet in the Netherlands!"
baseurl: "/zeppelin"
url: "http://cloudfest.gdgnl.app"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "GDG Cloud Netherlands"
organizerAlternateName: "Google Developer Group Cloud Netherlands"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "lviv@gdg.org.ua"
organizerLogo: "/img/organizers/GDGCloudLogo.png"
organizerLink: "http://gdgnl.app/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, cloud, gsuite, developers, amsterdam"
twitterAccount: "@gdgcloudnl"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://www.papercall.io/gdgcloudfest"
c4sponsorsUrl: "/assets/sponsordoc.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
rightNavigationButtons:
- {link: "http://gdgcloudfest.eventbrite.co.uk", text: "Get tickets"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "GDG Cloud<typeout>"
eventDate: "24th of November, 2018"
typeoutTextValues: '"", "Fest", "Fest Netherlands"'
typeoutFallback: "Fest Netherlands"
heroButtons:
 - {link: "https://www.eventbrite.co.uk/e/gdg-cloudfest-netherlands-tickets-28827047475", text: "Get tickets"}

# About Block
aboutTitle: "About GDG CloudFest"
aboutBlock:
 - {title: "Accesible", image: "talking.png", text: "Everyone is welcome, and we have talks for both beginners and advanced developers." }
 - {title: "Technical", image: "talks.png", text: "Everyone is welcome, but this is a technical conference. Expect technical talks." }
 - {title: "Community", image: "community.png", text: "Everyone is welcome! GDG is a global community. Learn from and with other Google developers." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "250", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "7", specialCharacter: "", info: "hours", detail: "of Google Cloud"}
 - {count: "12", specialCharacter: "+", info: "speakers", detail: "from the Netherlands and beyond"}
 - {count: "3", specialCharacter: "", info: "tracks", detail: "with both talks and workshops"}


# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Meet our speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "B.Amsterdam"
eventLocationLink: "http://b-buildingbusiness.com/amsterdam/"
eventStreetAddress: "Johan Huizingalaan 763a"
eventAddressLocality: "Amsterdam"
eventAddressLocalityRegion: "North-Holland"
eventPostalCode: "1066 VH"
eventAddressCountry: "The Netherlands"
eventStartTime: "2018-11-24T10:00"
eventDoorTime: "09:00"
eventEndTime: "2018-11-24T17:00"
eventPlaceCoordinates: "52.3431327, 4.8291255"
mapCenterCoordinates: "52.3431327, 4.8291255"
mapMobileCenterCoordinates: "52.3431327, 4.8291255"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "B.Amsterdam"
venueFeatures: ["Biggest tech startup ecosystem of Europe", "Three spacious conference rooms", "Easy to reach with both public transport and car"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "GDGCloudFest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=gdgcloudnl", icon: "twitter"}
 - {link: "https://facebook.com/gdgcloudnl", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://gdgnl.app", text: "GDG Netherlands"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:canelaguil@gmail.com", text: "Email Us"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google Developer Group Cloud Netherlands is part of the Global Groups of Google Technology enthusiasts. We just love Google Cloud Platform a lot. "

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Find your way to B.Amsterdam!"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transport", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

